### PR TITLE
Query Sorting

### PR DESCRIPTION
**Pull request by fonkadelic**
This addresses an issue i've came across by using a list of query items with the following format:
```
?key[0]=a&key[1]=b&key[2]=c
```

As soon as the list grows to 10+ elements the result looks like this:
```
?key[0]=a&key[10]=z&key[1]=b
```

Since certain backends require a specific order of the query items especially when it comes to list indices it's probably a good idea to use a different comparison function for the sorting.

I've introduced a _comparator_ on `URLQueryItem` which is basically just an alias for a string comparison function that respects number values. It can be reused across the library to get a consistent sorting behavior.

### CODE REVIEW

**Comment by stephencelis** [comment]
@fonkadelic Backend requirements never cease to surprise 😆

Instead of sorting, maybe we should just respect the ordering of both the parsed/printed query string. This would require changing the `Fields`' type to use an array instead of a dictionary. Wanna give that a try instead? If not, we could open a dedicated issue to track the problem and will try to tackle it in the future.

**Comment by fonkadelic** [comment]
I already gave it a try to use an array instead of of a dictionary. But i immediately got stuck since a lot of parts rely heavily on dictionary features. 

I'm really struggling when it comes to things like the [`subscript`](https://github.com/pointfreeco/swift-url-routing/blob/main/Sources/URLRouting/URLRequestData.swift#L120) in the `Fields` type or the [printer](https://github.com/pointfreeco/swift-url-routing/blob/main/Sources/URLRouting/Printing.swift#L86). I don't see a way to use an array here.

The only thing that comes to my mind would be an [`OrderedDictionary](https://github.com/apple/swift-collections/blob/main/Documentation/OrderedDictionary.md) but i'm not sure if the sorting issue justifies the introduction of a dependency.

**Comment by fonkadelic** [comment]
@stephencelis @mbrandonw Additional feedback from your side would be highly appreciated in order to move forward here.

**Comment by stephencelis** [comment]
@fonkadelic Sorry about that! We totally lost track of this issue. We are both OK with introducing `swift-collections` to the library to address things. Were you able to make good progress there?

**Comment by fonkadelic** [comment]
@stephencelis No worries!

I've swapped out the `Fields`' dictionary for an ordered dictionary and the result looks quite promising. I think the behavior is now really similar to `URLComponents` which also has it's query items ordered (`[URLQueryItem]`).

One thing i would like to discuss though is the fact that printing query items will happen in reverse order (due to the builder syntax):

```swift
let p = Query {
  Field("a")
  Field("b")
  Field("c")
}

let data = try p.print(("1", "2", "3"))
print(data.query) // ["c": ["3"], "b": ["2"], "a": ["1"]]
```

I've noticed this is essentially the same problem that the `Path` printer already solved by introducing a dedicated `PathBuilder`. Do you think we should go a similar route here?

**Comment by stephencelis** [comment]
@fonkadelic I think this is more due to the fact that parser printers should print via _prepending_ when doing so into collections. Now that we don't sort automatically, we should be more careful.

In particular, I believe this line should be updated:

https://github.com/pointfreeco/swift-url-routing/blob/6baa0179d6a8aefcbd50ec137db73b6632b9721e/Sources/URLRouting/Field.swift#L106

To this:

```swift
    try input.fields.updateValue(
      forKey: input.isNameCaseSensitive ? self.name : self.name.lowercased(),
      insertingDefault: [],
      at: 0,
      with: { $0.prepend(try self.valueParser.print(output)) }
    )
```

Which will preserve the expected order.

The name case sensitivity behavior of `Fields` does bother me a bit, and the fact we need to be mindful about it in yet another place here. Case-insensitivity is only enabled for headers, and as a result we have an existing bug to solve: https://github.com/pointfreeco/swift-url-routing/issues/12

I think this issue already exists, though, and doesn't need to block this PR. Wanna try the above code snippet and see if that fixes things?

**Comment by fonkadelic** [comment]
@stephencelis Looking good. Thanks for the push in this direction.

**Comment by stephencelis** [comment]
Thanks!

**Pull request merged**
