### PR TITLE
Add URL Scheme parser and test

### PR DESCRIPTION
**Pull request by ryanbooker**
## 💬 Summary of Changes

- Implements a scheme parser to support routing older style custom schemes on iOS.

## ✅ Checklist

- [x] 🧐 Performed a self-review of the changes.
- [x] ✅ Added tests to cover changes.
- [x] 🏎 Ran Unit Tests before opening PR.

### CODE REVIEW

**Comment by stephencelis** [comment]
@ryanbooker Thanks for taking the time to PR! There was a similar one opened [here](https://github.com/pointfreeco/swift-parsing/pull/207) before we extracted the library that was closed in favor of the `baseURL` and `baseRequestData` methods. Curious if you agree with this or if you have some example uses of where parsing the scheme can be useful?

I think generally the most important _parsers_ are the ones that can change throughout a single server process, and that nginx/Apache are kind of responsible for the server-level things, like scheme, host, etc.

**Comment by robfeldmann** [comment]
> Curious if you agree with this or if you have some example uses of where parsing the scheme can be useful?

I've been thinking about this too. I think being able to parse any part of the URL components is useful. For example, I have a need to parse/match the `fragment` of a URL for deep linking purposes, so I'm working on a `Fragment` ParserPrinter (although it's taking me an embarrassing amount of time to get it right).

I would also like to add a `Host` parser for the same reason. I can see needing to be able match on a custom scheme as well, even if it isn't suitable or recommended for printing/routing.

**Comment by ryanbooker** [comment]
Thanks for the response @stephencelis. I'm not sure I quite follow, and I've only been using the Library for "5 min" so if there's another way to do what I want, please point me at it! 😄 

I want to _parse_ a specific custom scheme on the app side (ignoring the fact that Apple discourages using them nowadays).

I'm working with some legacy code where the schemes can't be changed at the moment, and there are several custom schemes that have been used as routes. So rather than `customScheme://route1`, `customScheme://route2`, I have `route1://` and `route2://`.

I want to parse a specific schemes and the parser should fail if the scheme doesn't match… 

I can obviously just keep the Scheme parser in my local code, but thought it may be useful for others. 😅

**Comment by stephencelis** [comment]
> UPDATE: Turns out I misread the current code, and there is only one `Scheme`, however all the routes are based on the `Host` rather than a `Path`. e.g.`customerSceheme://route1` and `customScheme://route2`. I can add a similar `Host` parser if you decide either of these are useful/nice to have. 🙂

Typically if you want a path you would use `customScheme:///route1`, etc., but I can see that if it's out of your control a host parser could be useful...I think the thing we want to figure out is accidental misuse, _e.g._, if you use `Host(…)` or `Scheme(…)` because you want them to print in your routes, `baseURL` is often more appropriate, but docs can probably steer people the right direction.

Because of this, I think we'll take this after all! If you create a `Host` parser, please do submit a PR for it!

**Review by stephencelis — APPROVED** [review]

**Comment by ryanbooker** [comment]
Cool. No worries. I'll make a `Host` version as well. Thanks. :) `customScheme:///route1` makes sense, but the urls aren't really under my control, at least in the short term. Cheers. :)

**Pull request merged**
